### ISSUE TITLE
Problem had with instructions.

### ISSUE THREAD

**Issue by Cr-Un** [catppuccin/waybar#1]
Referring to 'Usage', the line:
`@import "$HOME/.config/waybar/<flavour>.css";`
has to be included in `style.css`.
But since waybar checks for files in it's config folder by default, `<string>` in `@import "<string>";` counts as file name and thus creates this error when launched:
`[error] style.css:7:42Failed to import: Error opening file ~/.config/waybar/$HOME/.config/waybar/<flavour>.css: No such file or directory`

Suggestion: Edit `@import "$HOME/.config/waybar/<flavour>.css";` to just `@import "<flavour>.css";`

There may be other ways to resolve this but I only know the slightest bit of how the program work.

**Comment by ohxxm** [comment]
I had this same issue and fixed it by doing this 
`@import "themes/mocha.css";` since I had the file in a folder but if you have it in the root directory you can do `@import "<flavour>.css"`.
