### ISSUE TITLE
Installing Catppuccin Waybar theme

### ISSUE THREAD

**Issue by enoren5** [catppuccin/waybar#12]
As far as I can tell, the installation instructions here on this Catppuccin Waybar themeing project look easy to follow but I am missing something.  I have followed the 4 steps as closely as I can and have referred to the Q+A and I can't succesfully apply the theme to my Waybar. I am not sure what I am doing wrong.

Here is exactly what I have done so far:
1. Downloaded the source code from the repo.
2. Copied the contents to `~/.config/waybar/`
3. Inside `style.css` at the @ import line I have specifid the flavour. In my case I chose: "frappe.css".

The next  step is what throws me off. The README instructions suggest:

4. Use the colors in your Waybar `style.css`  in this way:

```
* {
  /* reference the color by using @color-name */
  color: @text;
}

window#waybar {
  /* you can also GTK3 CSS functions! */
  background-color: shade(@base, 0.9);
  border: 2px solid alpha(@crust, 0.3);
}
```
What does that first the CSS comment mean? I tried adding `color:@frappe;` to the code block with the asterisk in my `config`. Didn't work. I kept it as `color:@ text;` as well. Also didn't work. Not sure what the author of that `README.md` is referring to when they say `@color-name` because I tried adding the theme name (frappe) as the value to the color property. It's still not working. What else could I try?

Please note: After making each change, I exited Sway and restarted it. No dice.

To quote the README.md for this Waybar project, it clearly does say refer to the official GTK3 docs:

>  Waybar uses [GTK3 CSS](https://docs.gtk.org/gtk3/css-overview.html#colors).

But after exploring the other issues, another user in #11 for this project asked:

> Seeing as the old example config is broken, could it be replaced by a working one with similar aesthetics?

Does this mean that the example config might be broken due to a breaking change recently introduced in an update for the GTK project? Is that why I am having trouble getting Waybar to theme properly?

According to [Catppuccin Issue #262](https://github.com/catppuccin/gtk/issues/262), the maintainers earlier this year decided to archive that project because themeing GTK became impractical. If that is what has happened to Catppuccin GTK is the issue I have encountered the same for Catppuccin Waybar? I would happily issue a PR with a fix but I am not sure what changes I need to make. Perhaps if Catppuccin Waybar customization is no longer possible or if the current instructions are outdated and no one is able to step forward with a PR, maybe this project should be archived similar to the Catppuccin GTK project.

**Comment by kjnsn** [comment]
You're so close with " I tried adding the theme name (frappe) as the value to the color property". Colors are things like red, green, mauve, lavender etc. See what colors catppuccin provides at https://catppuccin.com/palette

**Comment by enoren5** [comment]
Thank you, @kjnsn! That is clear now. I settled with "Maroon". That seems to square away the issue involving choosing the right colors. However Waybar is still not showing when I start Sway. I am not 100% sure why although my _hunch_ is that especially given #11 that the sample Waybar config linked to in the README is no longer up to date. Below are my configuration files. I am open to suggestions and feedback on how to get Waybar to show but since PR's may be required to update the internals of the Waybar configuration file, I gather this is the end of the road for me here. 

To be clear, I am not complaining. I appreciate @rubyowo's project so far. As with all open source projects, code is provided 'as-is' without express warranty. As Linus Torvalds famously quipped: `…the Linux philosophy is "laugh in the face of danger". Oops. Wrong one. "Do it yourself". That's it.` That really is the core of the open source community - -  the notion of self reliance. It's not a fair expectation to ask maintainers to build features for free. Maybe one day when I have enough Sway-Wayland configuration chops I will return here with multiple PR's to contribute. For now I may need to look for Waybar dotfiles elsewhere. I digress.

I have starred and and am watching this repo and will get updates whenever there is more activity.

For what it is worth, here are my current configuration files in full:

**~/.config/waybar/config**:
```
{
    "layer": "top", // Waybar at top layer
    "position": "top", // Waybar position (top|bottom|left|right)
    // "width": 1280, // Waybar width
    // Choose the order of the modules
    "modules-left": ["wlr/workspaces"],
    "modules-center": ["custom/music"],
    "modules-right": ["pulseaudio", "backlight", "battery", "clock", "tray", "custom/lock", "custom/power"],
    "wlr/workspaces": {
         "disable-scroll": true,
         "sort-by-name": true,
         "format": " {icon} ",
         "format-icons": {
             "default": "",
         },
     },
    "tray": {
        "icon-size": 21,
        "spacing": 10
    },
    "custom/music": {
        "format": "  {}",
        "escape": true,
        "interval": 5,
        "tooltip": false,
        "exec": "playerctl metadata --format='{{ title }}'",
        "on-click": "playerctl play-pause",
        "max-length": 50
    },
    "clock": {
        "timezone": "Asia/Dubai",
        "tooltip-format": "<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>",
        "format-alt": " {:%d/%m/%Y}",
        "format": " {:%H:%M}"
    },
    "backlight": {
        "device": "intel_backlight",
        "format": "{icon}",
        "format-icons": ["", "", "", "", "", "", "", "", ""]
    },
    "battery": {
        "states": {
            "warning": 30,
            "critical": 15
        },
        "format": "{icon}",
        "format-charging": "",
        "format-plugged": "",
        "format-alt": "{icon}",
        "format-icons": ["", "",  "", "", "", "", "", "", "", "", "", ""]
    },
    "pulseaudio": {
        // "scroll-step": 1, // %, can be a float
        "format": "{icon} {volume}%",
        "format-muted": "",
        "format-icons": {
            "default": ["", "", " "]
        },
        "on-click": "pavucontrol"
    },
    "custom/lock": {
        "tooltip": false,
        "on-click": "sh -c '(sleep 0.5s; swaylock --grace 0)' & disown",
        "format": "",
    },
    "custom/power": {
        "tooltip": false,
        "on-click": "wlogout &",
        "format": "襤"
    }
}
```
 **~/.config/waybar/style.css**:
```
@import "frappe.css";

* {
  font-family: FantasqueSansMono Nerd Font;
  font-size: 17px;
  min-height: 0;
}

#waybar {
  background: transparent;
  color: @Maroon;
  margin: 5px 5px;
}

#workspaces {
  border-radius: 1rem;
  margin: 5px;
  background-color: @surface0;
  margin-left: 1rem;
}

#workspaces button {
  color: @lavender;
  border-radius: 1rem;
  padding: 0.4rem;
}

#workspaces button.active {
  color: @sky;
  border-radius: 1rem;
}

#workspaces button:hover {
  color: @sapphire;
  border-radius: 1rem;
}

#custom-music,
#tray,
#backlight,
#clock,
#battery,
#pulseaudio,
#custom-lock,
#custom-power {
  background-color: @surface0;
  padding: 0.5rem 1rem;
  margin: 5px 0;
}

#clock {
  color: @blue;
  border-radius: 0px 1rem 1rem 0px;
  margin-right: 1rem;
}

#battery {
  color: @green;
}

#battery.charging {
  color: @green;
}

#battery.warning:not(.charging) {
  color: @red;
}

#backlight {
  color: @yellow;
}

#backlight, #battery {
    border-radius: 0;
}

#pulseaudio {
  color: @maroon;
  border-radius: 1rem 0px 0px 1rem;
  margin-left: 1rem;
}

#custom-music {
  color: @mauve;
  border-radius: 1rem;
}

#custom-lock {
    border-radius: 1rem 0px 0px 1rem;
    color: @lavender;
}

#custom-power {
    margin-right: 1rem;
    border-radius: 0px 1rem 1rem 0px;
    color: @red;
}

#tray {
  margin-right: 1rem;
  border-radius: 1rem;
}
```
 **~/.config/waybar/frappe.css**:
```
/*
*
* Catppuccin Frappe palette
* Maintainer: rubyowo
*
*/

@define-color base   #303446;
@define-color mantle #292c3c;
@define-color crust  #232634;

@define-color text     #c6d0f5;
@define-color subtext0 #a5adce;
@define-color subtext1 #b5bfe2;

@define-color surface0 #414559;
@define-color surface1 #51576d;
@define-color surface2 #626880;

@define-color overlay0 #737994;
@define-color overlay1 #838ba7;
@define-color overlay2 #949cbb;

@define-color blue      #8caaee;
@define-color lavender  #babbf1;
@define-color sapphire  #85c1dc;
@define-color sky       #99d1db;
@define-color teal      #81c8be;
@define-color green     #a6d189;
@define-color yellow    #e5c890;
@define-color peach     #ef9f76;
@define-color maroon    #ea999c;
@define-color red       #e78284;
@define-color mauve     #ca9ee6;
@define-color pink      #f4b8e4;
@define-color flamingo  #eebebe;
@define-color rosewater #f2d5cf;
```
