### ISSUE TITLE
Config file in screenshots?

### ISSUE THREAD

**Issue by Muvkina** [catppuccin/waybar#4]
Hey! This is awesome however I was wondering could you post the config used in the screenshots I love the rounded corners and dots and such.

**Comment by Muvkina** [comment]
I found it sorry about that

**Comment by z0rielle** [comment]
Where do you found it, can you share it?

**Comment by Muvkina** [comment]
Seems to be from the main contributors dotfiles:
https://github.com/rubyowo/dotfiles

**Comment by z0rielle** [comment]
Thankyou
