### ISSUE TITLE
How do i set this exactly like the screenshots?

### ISSUE THREAD

**Issue by bushyice** [catppuccin/waybar#8]
These are just the colors... and they aren't even working, how do i even use @COLOR?

**Comment by rubyowo** [comment]
Do you perhaps want the dotfiles of that exact setup

**Comment by kavyadeepdev** [comment]
Hey @rubyowo sorry for bothering you... but is there any way you could provide me with the dotfiles for that exact waybar setup? I would really appreciate it, thank you!

**Comment by bushyice** [comment]
Hey @rubyowo, yes please, can you send the dotfiles?

**Comment by 42willow** [comment]
Here: https://github.com/rubyowo/dotfiles/tree/main/config/waybar
